Check if symlink exists instead of spamming the console
cs3org/reva pull request #1992
Opened 2021-08-13 13:34 UTC by butonic

The logs have been spammed with messages like `could not create symlink for ...` when using the decomposedfs, eg. with the oCIS storage. We now check if the link exists before trying to create it.

deprecates https://github.com/cs3org/reva/pull/1988

2021-08-13 13:41 UTC, C0rby requested changes

2021-08-13 13:41 UTC, C0rby commented on pkg/storage/utils/decomposedfs/tree/tree.go
> +	spacesPath := filepath.Join(t.root, "spaces/"+spaceType, spaceID)
```suggestion
	spacesPath := filepath.Join(t.root, "spaces", spaceType, spaceID)
```

2021-08-13 13:45 UTC, butonic commented on pkg/storage/utils/decomposedfs/tree/tree.go
> +	spacesPath := filepath.Join(t.root, "spaces/"+spaceType, spaceID)
🤦

2021-08-16 06:45 UTC, labkode approved these changes

2021-08-16 06:45 UTC, merged