move unwrapping and wrapping of paths to the gateway
cs3org/reva pull request #2016
Opened 2021-08-24 13:29 UTC by C0rby

2021-09-01 13:59 UTC, refs requested changes
Hm, logging in doesn't seem to work for me on this PR. I flushed `/var/tmp/ocis` but still nothing, when rebuilding the entire tree it only creates directories

2021-09-23 13:36 UTC, refs submitted a review, later dismissed

2021-10-12 14:38 UTC, butonic commented
fixes https://github.com/cs3org/reva/issues/578

2021-11-02 08:40 UTC, butonic commented
started an acceptance test in https://github.com/cs3org/reva/pull/2219

2021-11-08 10:06 UTC, dragotin commented
Tests from @butonic in #2219 are merged. Can we continue on this one?

2021-12-07 11:31 UTC, butonic commented
merged in edge as part of https://github.com/cs3org/reva/pull/2234

2021-12-07 11:31 UTC, closed without merging