Filter root path according to the agent that makes the request
cs3org/reva pull request #2212
Opened 2021-10-27 09:22 UTC by gmgigi96

2021-11-04 13:22 UTC, ishank011 requested changes

2021-11-04 13:22 UTC, ishank011 commented on internal/grpc/services/gateway/gateway.go
> +	HiddenRootFolders   map[string][]string               `mapstructure:"hidden_root_folders"`
Have it the other way round, `path -> userAgentList`. Call it `AllowedUserAgents`

2021-11-04 13:22 UTC, ishank011 commented on internal/grpc/services/gateway/gateway.go
> +	hiddenRootFolders map[string]map[string]struct{}
Let's just store the map as passed by the user. At max, the list will contain 5 elements, searching over those won't lead to any performance drawback

2021-11-04 13:22 UTC, ishank011 commented on internal/grpc/services/gateway/storageprovider.go
> +func (s *svc) filterProvidersByUserAgent(ctx context.Context, providers []*registry.ProviderInfo) []*registry.ProviderInfo {
Move this logic to the useragent pkg. It should expose only one method `IsUserAgentAllowed(userAgent, allowedUserAgents) bool`

2021-11-04 13:22 UTC, ishank011 commented on internal/grpc/services/gateway/storageprovider.go
> +	if path.Clean(p) == "/" {
Move this code to `listContainerAcrossProviders`. That method is called when there are more than one provider matching a requested path. And there you don't need to call `getPath` as the requests will always be by path. And you can remove the root folder check as well

2021-11-04 13:22 UTC, ishank011 commented on pkg/ctx/agentctx.go
> +const UserAgentHeader = "x-user-agent"
Don't use a separate header. It's logged in other places so we should display the one we're adding

2021-11-04 13:22 UTC, ishank011 commented on pkg/rgrpc/rgrpc.go
> +		useragent.NewUnary(),
Move this above the log unary. I tried to move it above that but I still see the `grpc-go` agent being logged
`2021-11-04 14:00:55.491 DBG ../../internal/grpc/interceptors/log/log.go:69 > unary code=OK end="04/Nov/2021:14:00:55 +0100" from=tcp://127.0.0.1:52341 pid=46490 pkg=rgrpc start="04/Nov/2021:14:00:55 +0100" time_ns=2803304 uri=/cs3.storage.provider.v1beta1.ProviderAPI/ListContainer user-agent=grpc-go/1.26.0`

2021-11-04 13:41 UTC, ishank011 commented
Why don't we use this [here](https://github.com/cs3org/reva/blob/master/pkg/rgrpc/todo/pool/pool.go#L88)?
https://github.com/grpc/grpc-go/issues/1100#issuecomment-372132051

`server := grpc.Dial(grpc_server, WithUserAgent("user-agent",))`

2021-11-09 10:06 UTC, gmgigi96 commented
> Why don't we use this [here](https://github.com/cs3org/reva/blob/master/pkg/rgrpc/todo/pool/pool.go#L88)? [grpc/grpc-go#1100 (comment)](https://github.com/grpc/grpc-go/issues/1100#issuecomment-372132051)
> 
> `server := grpc.Dial(grpc_server, WithUserAgent("user-agent",))`

I will leave a comment here to keep track on what we discussed yesterday and other thought I have after playing with user agents in GRPC.

Actually this is the way of specifying a user agent in a grpc call, that internally updates the outcoming metadata in the context when you will call a grpc method, and you can find the user agent in the incoming metadata in the context server-side. But, even if you specify your own user agent, this will be concatenated with the string "grpc-go/<version>". I do not know if this can broke the library we use to parse the user agents, maybe not. But the main problem of using this approach is that for each time you want to get a grpc client for a service you need to specify the user agent that will do the request, if not specified, grpc automatically will set its default ("grpc-go/<version>"). This means that we should modify all the methods in the pool pkg to receive a user agent. But I do not like this approach as we cannot cache anymore the grpc connection for each endpoint address, but we should cache also the user agent. In fact after a dial, there is no way to override it after creating a new connection (I tried also modifying the internal metadata of a context before a call, but apparently grpc reset it with the user agent passed to the Dial method).

So I preferred to define my own user agent token that will be managed internally by reva and not by grpc. With this approach we do not have the cons mentioned above. Of course the user agent log did not work, as it was reading the grpc user-agent metadata, and not the new one. Now it’s fixed and you should see the correct user agent in the log.

2021-11-17 13:27 UTC, ishank011 approved these changes

2021-11-17 13:27 UTC, merged