fix idp schema, add virtual setup
cs3org/reva pull request #2219
Opened 2021-10-29 14:32 UTC by butonic

This just adds a config for the virtual views. The local integration tests now have two storage providers mounted at `/virtual` with the local driver. They can be accessed via the frontent-global service.

2021-11-01 15:45 UTC, butonic commented
ok, I am now checking if the etage of `/`, `/virtual` and `/virtual/b` changes when the folder `/virtual/b/bar` is created.

Unfortunately, not even this basic test works, I assume becaus I am using the local driver which
1. did not do a propagation when creating a dir (fixed in this PR)
2. does not seem provide an etag for the root of the storage ... or I am not fully understanding how the stat and list across providers code works...

when doing a PROPFIND against the virtual folder I should see the etag thet corresponds to the later provider entry, like this:
```
diff --git a/internal/grpc/services/gateway/storageprovider.go b/internal/grpc/services/gateway/storageprovider.go
index dcfd7be3..5292ac30 100644
--- a/internal/grpc/services/gateway/storageprovider.go
+++ b/internal/grpc/services/gateway/storageprovider.go
@@ -1334,7 +1334,14 @@ func (s *svc) statAcrossProviders(ctx context.Context, req *provider.StatRequest
                }
                if resp.Info != nil {
                        info.Size += resp.Info.Size
-                       info.Mtime = utils.LaterTS(info.Mtime, resp.Info.Mtime)
+                       if utils.TSToUnixNano(resp.Info.Mtime) > utils.TSToUnixNano(info.Mtime) {
+                               info.Mtime = resp.Info.Mtime
+                               info.Etag = resp.Info.Etag
+                               info.Checksum = resp.Info.Checksum
+                       }
+                       if info.Etag == "" && info.Etag != resp.Info.Etag {
+                               info.Etag = resp.Info.Etag
+                       }
                }
        }
 
@@ -1705,7 +1712,14 @@ func (s *svc) listContainerAcrossProviders(ctx context.Context, req *provider.Li
                                }
                                // TODO(ishank011): aggregrate properties such as etag, checksum, etc.
                                p.Size += info.Size
-                               p.Mtime = utils.LaterTS(p.Mtime, info.Mtime)
+                               if utils.TSToUnixNano(info.Mtime) > utils.TSToUnixNano(p.Mtime) {
+                                       p.Mtime = info.Mtime
+                                       p.Etag = info.Etag
+                                       p.Checksum = info.Checksum
+                               }
+                               if p.Etag == "" && p.Etag != info.Etag {
+                                       p.Etag = info.Etag
+                               }
                                p.Type = provider.ResourceType_RESOURCE_TYPE_CONTAINER
                                p.MimeType = "httpd/unix-directory"
                        } else {
```

right @ishank011 ?

Anyway, we should add the expectations to this PRs feature. Hopefully, it can be mimicked using the localfs.

2021-11-01 15:51 UTC, butonic commented
without the above diff I get
```
      WebDavPropertiesContext::theseEtagsShouldHaveChanged
      The etag '' of element '/' of user 'einstein' did not change.
      The etag '' of element '/virtual' of user 'einstein' did not change.
      The etag '"0330f2019a2524fc51bc62964a186ac4"' of element '/virtual/b' of user 'einstein' did not change.
      Failed asserting that 3 matches expected 0.
```

with it I can get rid of the last etag not changing:
```
      WebDavPropertiesContext::theseEtagsShouldHaveChanged
      The etag '' of element '/' of user 'einstein' did not change.
      The etag '' of element '/virtual' of user 'einstein' did not change.
      Failed asserting that 2 matches expected 0.
```

2021-11-02 09:00 UTC, individual-it requested changes
are these tests reva specific or should they be moved/copied to ocis?

2021-11-02 10:26 UTC, butonic commented on tests/acceptance/features/apiVirtualViews/virtualViews.feature
> +    Given user "einstein" has created the following folders
I tonly happens when users are created. But for this suite I am using the demo users. So, I need to manually restore the initial virtual folders in the background step.

2021-11-02 10:27 UTC, butonic commented
> are these tests reva specific or should they be moved/copied to ocis?

They are reva specific. The 'virtual views' feature allows *merging* multiple storage providers to serve a single folder. Not something owncloud 10 can do.

2021-11-02 10:28 UTC, individual-it commented on tests/acceptance/features/apiVirtualViews/virtualViews.feature
> +    Given user "einstein" has created the following folders
Any reason not to create "Alice" and delete the let the test suite delete the end?

2021-11-03 10:34 UTC, butonic commented
@ishank011 I think we have a passing test! 🤞

2021-11-03 11:13 UTC, ishank011 approved these changes

2021-11-03 11:17 UTC, C0rby approved these changes

2021-11-03 11:19 UTC, individual-it reviewed
I would suggest not to use "einstein" as user in the tests but create a new user as we do everywhere else

2021-11-03 11:21 UTC, individual-it commented on tests/acceptance/features/apiVirtualViews/virtualViews.feature
> +      | name                              |
table formatting could be improved

2021-11-03 11:31 UTC, butonic commented
> I would suggest not to use "einstein" as user in the tests but create a new user as we do everywhere else
I did not want to make an ldap server necessary as I don't want to test managing users. I would actually like to reduce this test to a point where we only register the storage providers and don't even have users ... but I would have to test further if disabling user home creation on login is enough.

2021-11-03 11:34 UTC, butonic commented
hm ... we could change the config of the default test suite to start two storage providers for /users .... but that would make the setup even more complex ...

2021-11-03 11:38 UTC, ishank011 approved these changes

2021-11-03 11:44 UTC, merged