Populate owner data in the ocs and ocdav services
cs3org/reva pull request #2233
Opened 2021-11-03 15:52 UTC by ishank011

2021-11-04 09:24 UTC, butonic commented
only fetch owner info when needed

2021-11-04 09:28 UTC, butonic requested changes
only fetch owner info when needed
```diff
diff --git a/internal/http/services/owncloud/ocdav/propfind.go b/internal/http/services/owncloud/ocdav/propfind.go
--- internal/http/services/owncloud/ocdav/propfind.go
+++ internal/http/services/owncloud/ocdav/propfind.go
@@ -482,15 +482,8 @@
 		)
 		sublog.Debug().Interface("role", role).Str("dav-permissions", wdp).Msg("converted PermissionSet")
 	}
 
-	var ownerUsername, ownerDisplayName string
-	owner, err := s.getOwnerInfo(ctx, md.Owner)
-	if err == nil {
-		ownerUsername = owner.Username
-		ownerDisplayName = owner.DisplayName
-	}
-
 	propstatOK := propstatXML{
 		Status: "HTTP/1.1 200 OK",
 		Prop:   []*propertyXML{},
 	}
@@ -593,8 +586,16 @@
 		}
 		// TODO return other properties ... but how do we put them in a namespace?
 	} else {
 		// otherwise return only the requested properties
+
+		var ownerUsername, ownerDisplayName string
+		owner, err := s.getOwnerInfo(ctx, md.Owner)
+		if err == nil {
+			ownerUsername = owner.Username
+			ownerDisplayName = owner.DisplayName
+		}
+
 		for i := range pf.Prop {
 			switch pf.Prop[i].Space {
 			case _nsOwncloud:
 				switch pf.Prop[i].Local {
```

2021-11-04 13:33 UTC, ishank011 commented
@butonic done!

2021-11-18 09:54 UTC, labkode approved these changes

2021-11-18 09:55 UTC, labkode submitted a review, later dismissed

2022-02-07 07:56 UTC, labkode approved these changes

2022-02-07 08:56 UTC, butonic approved these changes

2022-02-07 08:56 UTC, merged