Log traces only when these are available
cs3org/reva pull request #2352
Opened 2021-12-10 14:55 UTC by refs

Prevent from logging `traceid=0000000000000000`. Now logs would appear as:

![image](https://user-images.githubusercontent.com/6905948/145593715-2380d95d-62f7-490b-84ea-85f4fa59916a.png)

when traces are enabled, then the output looks like:

![image](https://user-images.githubusercontent.com/6905948/145593763-acc4ffd3-62e3-42f1-9a7d-3598a5983944.png)

as god intended.

2021-12-10 14:57 UTC, C0rby approved these changes

2021-12-10 15:35 UTC, kobergj commented on internal/grpc/interceptors/appctx/appctx.go
> +		traceID = ""
Why do overwrite an empty string with an empty string?

2021-12-10 15:37 UTC, kobergj commented on internal/http/interceptors/appctx/appctx.go
> +		traceID = ""
Same here. Why not just do
```
if span.SpanContext().TraceID() != [16]byte{} {
```

2021-12-10 15:38 UTC, kobergj requested changes

2021-12-10 15:38 UTC, kobergj commented on internal/http/interceptors/appctx/appctx.go
> +	if span.SpanContext().TraceID() == [16]byte{} {
Same here. Why not just do
```
if span.SpanContext().TraceID() != [16]byte{} {
```

2021-12-10 15:40 UTC, kobergj commented on pkg/rgrpc/status/status.go
> +	if span.SpanContext().TraceID() == [16]byte{} {
Maybe save `span.SpanContext().TraceID()` in its own var? It is used twice and that would make reading it simpler...

2021-12-10 15:49 UTC, kobergj commented on internal/grpc/interceptors/appctx/appctx.go
> +		return span.SpanContext().TraceID().String()
I'd suggest to do 
```go
if b := span.SpanContext().TraceID(); b != [16]byte{} {
     return b.String()
}
```
(in all three places). But it's not critical.

2021-12-13 14:30 UTC, refs commented
@kobergj thanks for the extra pair of eyes! I applied your suggestions, could you have another look? 🚀

2021-12-13 14:37 UTC, kobergj approved these changes
Looks awesome now :+1:

2021-12-13 14:41 UTC, labkode commented
@refs originally the traceid was not taken from the tracing framework, it was always visible as it was generated from a Reva middeware. With the change to the tracing framework we have now the possibility to configure a tracing target to send the traces remotely. 

However we should split two functionalities:
1) trace id in the log is always useful and should be available independently if the remote tracing collection is enabled or not.
2) send traces to remote collector for trace analysis.

With this in mind I'm not in favour of dropping the traceid rathen to fix the code to make sure it is always there

2021-12-13 14:42 UTC, labkode requested changes
Traceid should always be present in the logs independently if trace collector is enabled or not.

2021-12-13 14:52 UTC, refs commented
> Traceid should always be present in the logs independently if trace collector is enabled or not.

Hm, I see your argument of always having traces regardless of these are reported or not. I will update the code to reflect that. I completely misjudged the benefits of having the traces always available 👍

2021-12-13 15:43 UTC, ishank011 commented
@refs I'd propose enabling tracing by default if it has not been explicitly disabled

```diff
diff --git a/cmd/revad/runtime/runtime.go b/cmd/revad/runtime/runtime.go
index 22d55eb3..9783092c 100644
--- a/cmd/revad/runtime/runtime.go
+++ b/cmd/revad/runtime/runtime.go
@@ -311,6 +311,15 @@ func parseCoreConfOrDie(v interface{}) *coreConf {
                os.Exit(1)
        }

+       // tracing defaults to enabled if not explicitly configured
+       if v == nil {
+               c.TracingEnabled = true
+               c.TracingEndpoint = "localhost:6831"
+       } else if _, ok := v.(map[string]interface{})["tracing_enabled"]; !ok {
+               c.TracingEnabled = true
+               c.TracingEndpoint = "localhost:6831"
+       }
+
        return c
 }
```

2021-12-14 08:49 UTC, refs commented
That's a way to do it. I'm currently testing what would happen if there is no sidecar agent and we have traces. I have seen it fail trying to connect to the agent's address. Once I got it working I'll update here. But out of the box seems like a good compromise, if it works 👯

2021-12-14 08:56 UTC, refs commented
update: the exporter fails, and crashes if missconfigured. I will figure a way to preserve the traceid for the logs regardless of enabled tracing

2022-02-07 13:15 UTC, ishank011 commented
Superseded by https://github.com/cs3org/reva/pull/2515

2022-02-07 13:15 UTC, closed without merging