Implement touch file
cs3org/reva pull request #2369
Opened 2021-12-13 11:19 UTC by wkloucek

2021-12-14 13:16 UTC, glpatcern requested changes
Looks fine to me apart the mini typos. is this what will eventually be used by the appprovider `/app/new` workflow?

2021-12-14 13:16 UTC, glpatcern commented on internal/grpc/interceptors/readonly/readonly.go
> +				Status: rstatus.NewPermissionDenied(ctx, nil, "permission denied: tried to create ressource on readonly storage"),
```suggestion
				Status: rstatus.NewPermissionDenied(ctx, nil, "permission denied: tried to create resource on read-only storage"),
```

2021-12-14 13:16 UTC, glpatcern commented on internal/grpc/interceptors/readonly/readonly.go
> +				Status: rstatus.NewPermissionDenied(ctx, nil, "permission denied: tried to create ressource on readonly storage"),
```suggestion
				Status: rstatus.NewPermissionDenied(ctx, nil, "permission denied: tried to create resource on read-only storage"),
```

2021-12-14 13:19 UTC, wkloucek commented on internal/grpc/interceptors/readonly/readonly.go
> +				Status: rstatus.NewPermissionDenied(ctx, nil, "permission denied: tried to create ressource on readonly storage"),
Thanks :+1:

2021-12-14 14:55 UTC, glpatcern approved these changes

2021-12-15 09:47 UTC, C0rby approved these changes

2021-12-17 10:35 UTC, C0rby commented
@ishank011, could you have a look at this and merge it?
We want to implement the CS3API changes but there are 3 and they need to be merged in order.

This here is the first one. Then:
https://github.com/cs3org/reva/pull/2350
And last:
https://github.com/cs3org/reva/pull/2341

2021-12-17 11:02 UTC, labkode approved these changes

2021-12-17 11:02 UTC, merged