Consolidate all metadata Get's and Set's to central functions.
cs3org/reva pull request #2512
Opened 2022-02-07 11:48 UTC by dragotin

In the decomposed FS, access to xattr was spread all over. This
patch consolidates that to use either the Node.SetMetadata() or
xattrs.Set(). This allows us to hook in indexing for example.

This does not yet handle Remove, List and others. Subject of another patch.

2022-02-07 11:50 UTC, dragotin commented on pkg/storage/utils/decomposedfs/xattrs/xattrs.go
> +// The primitive function to set the extended attribute
@aduffeck FYI

2022-02-07 20:28 UTC, dragotin commented
Get, Set and All also give us a central point to deal with locking, indexing, plausability checks and logging.

2022-02-10 09:22 UTC, C0rby requested changes

2022-02-10 09:22 UTC, C0rby commented on pkg/storage/utils/decomposedfs/node/node.go
> +	attribs[xattrs.BlobsizeAttr] = fmt.Sprintf("%d", n.Blobsize)
```suggestion
	attribs[xattrs.BlobsizeAttr] = strconv.FormatInt(n.Blobsize, 10)
```

2022-02-10 09:22 UTC, C0rby commented on pkg/storage/utils/decomposedfs/xattrs/xattrs.go
> +}
```suggestion
func All(filePath string) (map[string]string, error) {
	attrNames, err := xattr.List(filePath)
	if err != nil {
		return nil, errors.Wrap(err, "xattrs: Can not list extended attributes")
	}

       attribs := make(map[string]string, len(attrNames))
	for _, name := range attrNames {
		val, err := xattr.Get(filePath, name)
		if err != nil {
			return nil, errors.Wrap(err, "Failed to read extended attrib")
		}
		attribs[name] = string(val)
	}

	return attribs, nil
}
```

2022-02-10 14:04 UTC, C0rby approved these changes

2022-02-10 14:04 UTC, merged