Reuse ocs role objects in other drivers
cs3org/reva pull request #2514
Opened 2022-02-07 13:03 UTC by ishank011

2022-02-08 11:54 UTC, gmgigi96 commented
This should fix https://github.com/cs3org/reva/issues/2521

2022-02-08 12:03 UTC, gmgigi96 requested changes
Hi @ishank011, I left some comments
Also you could fix this https://github.com/cs3org/reva/blob/master/internal/http/services/owncloud/ocs/conversions/role.go#L245 with the RoleUploader

2022-02-08 12:03 UTC, gmgigi96 commented on pkg/auth/scope/scope.go
> +	return scope.Role == authpb.Role_ROLE_OWNER || scope.Role == authpb.Role_ROLE_EDITOR || scope.Role == authpb.Role_ROLE_UPLOADER
I think it's better create two functions similar to this, one for checking the editor role and the other for uploader, and than while checking the publicshareScope for the `InitiateFileUploadRequest` check the hasRoleUploader also.

This also require that this function https://github.com/cs3org/reva/blob/master/internal/grpc/interceptors/auth/scope.go#L218 is aware of the uploader role (as is aware of the editor role)

2022-02-08 12:03 UTC, gmgigi96 commented on internal/grpc/interceptors/auth/scope.go
> +		if v.Role == authpb.Role_ROLE_OWNER || v.Role == authpb.Role_ROLE_EDITOR || v.Role == authpb.Role_ROLE_UPLOADER {
See the comment below

2022-04-20 07:58 UTC, labkode approved these changes

2022-04-20 07:58 UTC, merged