use nats jetstream
cs3org/reva pull request #2574
Opened 2022-02-21 16:03 UTC by wkloucek

2022-03-11 09:22 UTC, kobergj requested changes
Found some smaller ones...

2022-03-11 09:22 UTC, kobergj commented on internal/grpc/interceptors/eventsmiddleware/events.go
> +				log.Debug("event emitted just fine")
If we need this log, please also add an identifier which event was emitted fine. Otherwise the log is mostly useless.

2022-03-11 09:22 UTC, kobergj commented on internal/grpc/interceptors/eventsmiddleware/events.go
> +		return pub, err
What is the point in this change?

2022-03-11 09:22 UTC, kobergj commented on pkg/events/example/example.go
> +		server.Port(4222),
use `9233` as port for nats please

2022-03-11 09:22 UTC, kobergj commented on pkg/events/example/example.go
> +		natsjs.Address("127.0.0.1:4222"),
same here port `9233`

2022-03-11 09:22 UTC, kobergj commented on pkg/events/server/nats.go
> +		options,
can we have this in one line? I don't see the point in having this streched over multiple lines

2022-03-14 10:14 UTC, kobergj commented on pkg/events/server/nats.go
> +	server.EnableJetStream(c)
Linter is angry that we don't check the error
```suggestion
	_ = server.EnableJetStream(c)
```

2022-03-17 10:53 UTC, kobergj approved these changes

2022-03-22 21:36 UTC, butonic commented
we should update https://github.com/owncloud/ocis/pull/3192

2022-03-24 07:16 UTC, merged