Locks mutexed
cs3org/reva pull request #2582
Opened 2022-02-23 09:40 UTC by dragotin

There must be only one Flock struct per lock file. If that
is existing, no other routine or process may get a lock.

2022-02-23 13:46 UTC, glpatcern approved these changes
Looks good to me, though final word is for @butonic I guess. Will see if we can use (some of) this also in the EOS storage implementation, cs3org/reva#2444

2022-02-23 14:59 UTC, C0rby requested changes

2022-02-23 14:59 UTC, C0rby commented on pkg/storage/utils/filelocks/filelocks.go
> +		// fmt.Printf("Waiting for lock to release %d\n", w)
remove this comment

2022-02-24 10:34 UTC, C0rby approved these changes
Looks good! :+1:

2022-02-24 10:34 UTC, C0rby commented on pkg/storage/utils/filelocks/filelocks.go
>  }
Just a small nitpick. Remove empty function.

2022-02-24 11:31 UTC, micbar approved these changes

2022-02-24 11:42 UTC, merged