implement listing shares in spaces
cs3org/reva pull request #2622
Opened 2022-03-07 11:59 UTC by C0rby

Instead of the query parameter `path` one can now send `space_ref` to
list shares in spaces. The url would look like this:
`https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares?reshares=true&space_ref=ae96eb17-1b37-4bfc-8ed6-9c044723a43f/elmo.gif`

2022-03-14 08:53 UTC, wkloucek commented on tests/oc-integration-tests/local/ldap-users.toml
> +hostname="localhost"
that one shouldn't change?

2022-03-14 09:16 UTC, kobergj requested changes

2022-03-14 09:16 UTC, kobergj commented on pkg/utils/utils.go
> +// If ref or ref.ResourceId are nil an empty string will be returned.
Not quite true. It errors in that case.

2022-03-14 16:37 UTC, C0rby commented on pkg/utils/utils.go
> +// If ref or ref.ResourceId are nil an empty string will be returned.
Oh, true. Forgot to update the comment.

2022-03-15 08:23 UTC, kobergj approved these changes

2022-03-15 08:34 UTC, merged