Prevent recursive copy/move operations on the API level
cs3org/reva pull request #3009
Opened 2022-06-24 08:55 UTC by aduffeck

Fixes https://github.com/owncloud/ocis/issues/3992

2022-07-04 13:37 UTC, butonic requested changes
I see now why you were unhappy. Doing a GetPath request as the owner requires ocdav to know the machine auth api key ...

what would happen if we send the GetPath as the current user?

In theory the storage driver should give us a path relative to the same root when calling GetPath with two different references. Each call should look up the highest resourceid the user has access to and we should be able to compare the path. We can also check thet the references resourceid that we get in GetPath is the same ... dang ... GetPath has no resource id ... fck

I remember discussing having to extend GetPath with the space root for exactly this reason ... maybe in https://github.com/cs3org/reva/pull/1721#issue-897520929

Then again, we extended `ResourceInfo` with `Name` and could use the filedmask to query `Path` and `Space` in a Stat request instead of a GetPath request ... 🤔

2022-07-04 13:37 UTC, butonic commented on internal/http/services/owncloud/ocdav/ocdav.go
> +	parentAuthCtx, err := authContextForUser(client, parentStatRes.Info.Owner, s.c.MachineAuthAPIKey)
When the MachineAuthAPIKey is not set, can we return a `NotSupported` error? Then referenceIsChildOf or the move.go implementation can return a good error ur just return a forbidden error

2022-07-05 08:53 UTC, butonic approved these changes

2022-07-05 08:54 UTC, merged

2022-07-05 12:19 UTC, phil-davis commented
@aduffeck this is good and fixes the loop.

Now the related test fails because the API request returns HTTP status 400 in this case. But oC10 returns 409 in this case.

Is it easy to make another PR that adjusts the return status to 409?

See my updated issue https://github.com/owncloud/ocis/issues/3023 and PR #3030 that enables the test again.