Add user filter
cs3org/reva pull request #3046
Opened 2022-07-08 14:27 UTC by dragonchaser

This PR adds filters to filter spaces by user-id.

2022-07-08 14:47 UTC, butonic approved these changes

2022-07-14 12:41 UTC, butonic requested changes
we can do a better cleanup

2022-07-14 14:16 UTC, butonic approved these changes

2022-07-15 05:59 UTC, wkloucek requested changes

2022-07-15 05:59 UTC, wkloucek commented on go.mod
> +	github.com/owncloud/libre-graph-api-go => github.com/owncloud/libre-graph-api-go v0.14.4-0.20220711134340-f651467893e1
what does this do?

2022-07-15 10:11 UTC, dragonchaser commented on go.mod
> +	github.com/owncloud/libre-graph-api-go => github.com/owncloud/libre-graph-api-go v0.14.4-0.20220711134340-f651467893e1
copy & paste :disappointed:

2022-07-15 10:34 UTC, wkloucek approved these changes

2022-07-15 12:12 UTC, merged