Improve Dockerfile.revad-eos
cs3org/reva pull request #3197
Opened 2022-09-06 16:47 UTC by ebocchi

- Use EOS 4.8.91
- Bring back multi-stage build
- Copy the resulting revad from the builder container

Resulting image size (unpacked on disk) is 2.59GB
- eos-all:4.8.91 is 2.47GB
- existing revad:latest-eos is 6.18GB

2022-09-07 06:56 UTC, glpatcern approved these changes
Nice!

2022-11-17 10:02 UTC, jimil749 commented
/cc @SamuAlfageme can we get this merged, so that it can be used for Sciencebox?

2022-11-17 10:19 UTC, SamuAlfageme requested changes
@ebocchi the CI was failing due to a missing x-ref to the GitHub PR

2022-11-17 10:19 UTC, SamuAlfageme commented on changelog/unreleased/dockerfile.revad-eos.md
> +* existing revad:latest-eos is 6.18GB
```suggestion
* existing revad:latest-eos is 6.18GB

https://github.com/cs3org/reva/pull/3197
```

2022-12-01 16:08 UTC, glpatcern commented
@ebocchi I'm sorry to have screwed part of this change :-P can you please rebase it on top of `master` ?

2022-12-02 12:54 UTC, SamuAlfageme approved these changes

2022-12-02 12:58 UTC, ebocchi commented
@glpatcern 
Rebased against master. Should be good to go now ;)

2022-12-02 13:48 UTC, gmgigi96 commented
@ebocchi can you fix the linter (Codacy Static Code Analysis)?

2022-12-02 13:55 UTC, ebocchi commented
As per @glpatcern, going back to `eos-client-4.8.91-1.el7.cern.x86_64` as the only package needed is eos-client.
`eos-client-4.8.91-1.el7.cern.x86_64` include:
```
# rpm -qa | grep ^eos | sort
eos-client-4.8.91-1.el7.cern.x86_64
eos-folly-2019.11.11.00-1.el7.cern.x86_64
eos-folly-deps-2019.11.11.00-1.el7.cern.x86_64
eos-fusex-4.8.91-1.el7.cern.x86_64
eos-fusex-core-4.8.91-1.el7.cern.x86_64
eos-fusex-selinux-4.8.91-1.el7.cern.x86_64
eos-protobuf3-3.5.1-5.el7.cern.eos.x86_64
eos-xrootd-4.12.8-1.el7.cern.x86_64
```

2022-12-02 14:05 UTC, glpatcern approved these changes

2022-12-02 14:23 UTC, merged