introduce otel tracing
cs3org/reva pull request #3496
Opened 2022-11-25 15:41 UTC by butonic

I was toying with https://github.com/SigNoz/signoz which uses otel tracing. This PR allows configuring `tracing_exporter=otlp` as a trace exporter.

2023-05-25 10:26 UTC, Excds requested changes

2023-05-25 10:26 UTC, Excds commented on pkg/trace/trace.go
> +		opts := []otlptracegrpc.Option{
Please remove the commented out section.

2023-05-25 10:27 UTC, Excds commented
LGTM (except for the commented out section).

2023-05-25 12:16 UTC, aduffeck approved these changes

2023-05-26 10:59 UTC, fschade approved these changes
LGTM

2023-05-26 11:12 UTC, merged