Add UserTypeProperty to get user type from ldap user entry
cs3org/reva pull request #3744
Opened 2023-03-23 11:21 UTC by Excds

Adding an LDAP attribute UserTypeProperty to be able to distinguish between member and guest users.

2023-03-23 16:59 UTC, rhafer approved these changes

2023-03-23 17:00 UTC, rhafer requested changes
Please use the full URL of the PR in the changelog

2023-03-24 10:09 UTC, butonic approved these changes

2023-03-24 10:11 UTC, kobergj approved these changes

2023-03-24 10:11 UTC, kobergj commented on pkg/utils/ldap/identity.go
> +// GetUserType is used to set the proper UserType from ldap entry string
```suggestion
// GetUserType is used to get the proper UserType from ldap entry string
```

2023-03-24 10:11 UTC, micbar approved these changes

2023-03-24 10:27 UTC, merged