fix error during mkcol
cs3org/reva pull request #3834
Opened 2023-04-29 19:43 UTC by micbar

# Description

We need to return `409 Conflict` when one or more path elements during an MKCOL do not exist.

Fixes: https://github.com/owncloud/ocis/issues/6136

2023-04-29 20:57 UTC, micbar commented
@dragotin This is a fix to enable the usage of `rclone`

2023-04-30 06:44 UTC, glpatcern commented
@redblom do we need this in `master` or do we already have this behaviour?

2023-05-01 08:37 UTC, redblom commented
@micbar @glpatcern : I can confirm that `master` returns `409 Conflict` and rclone behaves as expected, it can create a complete new path.

2023-05-02 07:09 UTC, micbar commented
> @micbar @glpatcern : I can confirm that `master` returns `409 Conflict` and rclone behaves as expected, it can create a complete new path.

@redblom Can you check if this is also the case for non-existing sub-sub directories?

2023-05-02 07:54 UTC, butonic requested changes

2023-05-02 08:03 UTC, micbar commented on pkg/storage/utils/decomposedfs/decomposedfs.go
>  	if n, err = fs.lu.NodeFromResource(ctx, parentRef); err != nil {
Can you check why this is not working as you expect it? The problem is, that this only works on the first level.

2023-05-02 12:15 UTC, redblom commented
> @redblom Can you check if this is also the case for non-existing sub-sub directories?

@micbar Yes, also with sub/sub/sub directories, the response is always `409 Conflict` (message: `Parent node does not exist`)

2023-05-02 12:22 UTC, micbar commented on pkg/storage/utils/decomposedfs/decomposedfs.go
>  	if n, err = fs.lu.NodeFromResource(ctx, parentRef); err != nil {
done

2023-05-02 20:21 UTC, butonic approved these changes

2023-05-02 20:24 UTC, merged