The DeleteStorageSpace method response code has been changed
cs3org/reva pull request #3848
Opened 2023-05-04 20:29 UTC by 2403905

The DeleteStorageSpace method response status has been changed to 'not found' if no one spaces in a list or errtypes.IsNotFound. That allows us to handle the status properly.  Related to https://github.com/owncloud/ocis/issues/5031

2023-05-05 07:46 UTC, dragonchaser requested changes

2023-05-05 07:46 UTC, dragonchaser commented on internal/grpc/services/storageprovider/storageprovider.go
> +		if len(spaces) == 0 {
can't we write `len(spaces) > 0` in line 599 and put this in an else branch, would be easier to read IMHO. (just nitpicking sorry :))

2023-05-08 08:36 UTC, dragonchaser approved these changes

2023-05-08 10:01 UTC, kobergj requested changes

2023-05-08 10:01 UTC, kobergj commented on internal/grpc/services/storageprovider/storageprovider.go
> +	} else if len(spaces) != 1 {
```suggestion
	} else if len(spaces) == 1 {
```
If we need to handle `len(spaces) > 1` we should a separate case for it.

2023-05-08 11:49 UTC, closed without merging