Dont lose revisions when replacing
cs3org/reva pull request #3896
Opened 2023-05-16 15:12 UTC by aduffeck

We no longer delete-and-upload targets of copy operations but ratheradd a new version with the source content.

This makes "overwrite when copying" behave the same as "overwrite when uploading".

Overwriting when moving a file still deletes the old file (moves it into the trash) and replaces the whole file including the revisions of the source file.

Fixes https://github.com/owncloud/ocis/issues/4797

2023-05-16 15:20 UTC, micbar approved these changes

2023-05-16 17:13 UTC, micbar requested changes
The tests indicate that we change some expected behavior

2023-05-19 06:57 UTC, aduffeck commented
@micbar The failing tests expect a file to be turned into a folder when a fold is copied onto (into? over?) them. Is that really the expected behavior here or should we rather adapt the tests?
Doing this operation isn't possible using the web UI and tools like `cp` also bail out in cases like that.

2023-05-22 11:58 UTC, micbar commented
@aduffeck @individual-it Ok we need to change the test expectations.

2023-05-23 08:56 UTC, micbar approved these changes

2023-05-23 09:09 UTC, merged