Dont invalidate metadata cache
cs3org/reva pull request #4017
Opened 2023-06-28 12:21 UTC by aduffeck

This PR brings some performance tweaks and makes the code more robus when encountering invalid space root metadata.

2023-06-28 13:27 UTC, butonic approved these changes

2023-06-28 13:40 UTC, kobergj requested changes

2023-06-28 13:40 UTC, kobergj commented on pkg/storage/utils/decomposedfs/metadata/messagepack_backend.go
> +	return f.Close()
Don't we already `defer f.Close()` in line 142?

2023-07-06 14:07 UTC, butonic commented
@aduffeck I rebased. Not too many things left. And I created https://github.com/cs3org/reva/pull/4045 to move more into separate PRs.

2023-07-06 14:09 UTC, butonic commented
there are some hardcoded chache changes that we want to verify before this PR is ready

2025-01-21 07:49 UTC, closed without merging