Fix some tests
cs3org/reva pull request #4136
Opened 2023-08-25 14:53 UTC by michielbdejong

2023-08-25 14:56 UTC, michielbdejong commented
Actually now that i think about it, in [b71cffc](https://github.com/cs3org/reva/pull/4136/commits/b71cffc0f637be637414a132300552203edbe481) we changed the code instead of changing the mock, maybe we should have changed the mock to match what the current code does?

2023-08-25 14:58 UTC, michielbdejong commented
@MahdiBaghbani you can open a GitPod on this branch and run
```
go test -v github.com/cs3org/reva/pkg/ocm/share/repository/nextcloud
```
One thing you could try is to invert the change, so instead of making the owner & creator a UserId in the code, make it a user object in the mock!

2023-08-29 13:27 UTC, glpatcern requested changes
I guess it's better to go as @michielbdejong did initially, i.e. adapt the code to manipulate userIds as likely you don't have (nor do you need) the other metadata coming with `User`.

Nevertheless, there are two changes to be reverted.

2023-08-29 13:27 UTC, glpatcern commented on pkg/ocm/share/repository/nextcloud/nextcloud.go
> +		ResourceId: nil,
This was added to fix the access to remote resources, if you remove it the access is broken. Please revert ;)

2023-08-29 13:27 UTC, glpatcern commented on pkg/ocm/share/repository/nextcloud/nextcloud.go
> +
That is very temporary and should be reverted too...

2023-08-31 08:29 UTC, closed without merging

2023-08-31 08:29 UTC, glpatcern commented
Superseded

2023-08-31 16:40 UTC, glpatcern commented
@michielbdejong @MahdiBaghbani just to keep track of today's work: eventually we reverted this because it broke the code, so you need to change the mock and keep the code. Can you prepare another PR?