Reworked List() to support version folder fileid tricks
cs3org/reva pull request #4321
Opened 2023-11-08 13:49 UTC by ffurano

2023-11-08 14:13 UTC, glpatcern requested changes
We tested this, so it's all fine, yet I propose a few logging level changes, you see the pattern

2023-11-08 14:13 UTC, glpatcern commented on pkg/eosclient/eosgrpc/eosgrpc.go
> +	log.Info().Str("func", "GetFileInfoByInode").Str("uid,gid", auth.Role.UID+","+auth.Role.GID).Uint64("inode", inode).Msg("entering")
```suggestion
	log.Debug().Str("func", "GetFileInfoByInode").Str("uid,gid", auth.Role.UID+","+auth.Role.GID).Uint64("inode", inode).Msg("entering")
```

2023-11-08 14:13 UTC, glpatcern commented on pkg/eosclient/eosgrpc/eosgrpc.go
> +	log.Debug().Str("func", "GetFileInfoByInode").Uint64("inode", inode).Uint64("info.Inode", info.Inode).Str("file", info.File).Uint64("size", info.Size).Str("etag", info.ETag).Msg("result")
```suggestion
	log.Info().Str("func", "GetFileInfoByInode").Uint64("inode", inode).Uint64("info.Inode", info.Inode).Str("file", info.File).Uint64("size", info.Size).Str("etag", info.ETag).Msg("result")
```

2023-11-08 14:13 UTC, glpatcern commented on pkg/eosclient/eosgrpc/eosgrpc.go
> +	log.Info().Str("func", "GetFileInfoByPath").Str("uid,gid", auth.Role.UID+","+auth.Role.GID).Str("path", path).Msg("entering")
```suggestion
	log.Debug().Str("func", "GetFileInfoByPath").Str("uid,gid", auth.Role.UID+","+auth.Role.GID).Str("path", path).Msg("entering")
```

2023-11-09 12:47 UTC, gmgigi96 approved these changes

2023-11-09 13:00 UTC, merged