extract upload manager interface
cs3org/reva pull request #4375
Opened 2023-11-29 13:59 UTC by butonic

This is a little cleanup of the UploadProgress interface I had to introduce in https://github.com/cs3org/reva/pull/4148 

For now I just want to get initial feedback on the interface. This should be the first step towards a cli or background jobs that clean up expired uploads.
- [ ] When purging uploads we still need to skip uploads that are completet, but that have not been processed yet to prevent data loss. Can be done in a subsequent PR.
- [ ] We still need to filter the list of uploads by processing state. Currently, that is stored in the node metadata.

2023-11-30 07:33 UTC, aduffeck commented
The `TODO`s and `FIXME`s should be addressed or turned into issues before merging this in my opinion, but the general interface looks good to me.
How's the filtering of uploads gonna look like though? Does that become part of the `ListUploads()` call?

2023-11-30 14:57 UTC, butonic commented
tracking the tus upload-expires bug in https://github.com/cs3org/reva/issues/4379

2023-11-30 15:27 UTC, aduffeck commented
> @aduffeck I completely changed the upload interface. ...
> your opinion?

lgtm, as discussed in zoom :+1:

2023-11-30 15:49 UTC, kobergj requested changes
Generally looks good but the linter is not happy

Additional Question: Did you run a `full-ci` pipeline on ocis to make sure these changes don't break ocis pipeline?

2023-11-30 15:49 UTC, kobergj commented on pkg/storage/uploads.go
> +	ListUploadSessions(ctx context.Context, filter UploadSessionFilter) ([]UploadSession, error)
Wrong comment for method

2023-11-30 15:49 UTC, kobergj commented on pkg/storage/uploads.go
> +type UploadSessionFilter struct {
exported type UploadSessionFilter should have comment or be unexported

2023-11-30 15:49 UTC, kobergj commented on pkg/storage/utils/decomposedfs/upload/processing.go
> +func (p Progress) Reference() provider.Reference {
exported func Reference should have comment or be unexported

2023-11-30 15:49 UTC, kobergj commented on pkg/storage/utils/decomposedfs/upload/processing.go
> +func (p Progress) Executant() userpb.UserId {
exported func Executant should have comment or be unexported

2023-11-30 15:49 UTC, kobergj commented on pkg/storage/utils/decomposedfs/upload/processing.go
> +func (p Progress) SpaceOwner() *userpb.UserId {
exported func SpaceOwner should have comment or be unexported

2023-11-30 15:49 UTC, kobergj commented on pkg/storage/utils/decomposedfs/upload/processing.go
> +func (p Progress) Expires() time.Time {
exported func Expires should have comment or be unexported

2023-11-30 15:49 UTC, kobergj commented on pkg/storage/utils/decomposedfs/upload/processing.go
> +func (p Progress) IsProcessing() bool {
exported func IsProcessing should have comment or be unexported

2023-11-30 15:49 UTC, kobergj commented on pkg/storage/utils/decomposedfs/upload/processing.go
> +func (p Progress) Purge(ctx context.Context) error {
exported func Purge should have comment or be unexported

2023-11-30 15:49 UTC, kobergj commented on pkg/storage/utils/decomposedfs/upload/processing.go
> +	return os.Remove(p.Path)
Shouldn't we try to remove `p.Path` also when removing the binpath fails?

2023-11-30 15:49 UTC, kobergj commented on pkg/storage/uploads.go
> +type UploadSession interface {
exported type UploadSession should have comment or be unexported

2023-11-30 16:09 UTC, butonic commented
@kobergj I hope I made the linter happy ;-) will create an ocis bump right away

2023-11-30 17:43 UTC, kobergj approved these changes

2023-12-01 12:20 UTC, merged

2023-12-01 12:22 UTC, butonic commented
ocis pr was green, will rebase https://github.com/cs3org/reva/pull/4148 now