usershareprovider: check permissions before updating a share
cs3org/reva pull request #4405
Opened 2023-12-13 14:29 UTC by rhafer

Instead of relying on the calling service for permission checks, we're now checking if the requesting user has sufficient permission for performing an update in the shareprovider itself.

2023-12-13 15:16 UTC, kobergj requested changes

2023-12-13 15:22 UTC, rhafer commented on internal/grpc/services/usershareprovider/usershareprovider.go
> +		if newPermissions.GetDelete() || newPermissions.GetDelete() {
Yeah, stupid typo.

2023-12-14 10:28 UTC, rhafer commented
@micbar This should be ready now. I also did a [full-ci] run on ocis with it (see https://drone.owncloud.com/owncloud/ocis/30043)

2023-12-15 11:18 UTC, micbar approved these changes

2023-12-15 13:37 UTC, kobergj approved these changes

2023-12-15 13:47 UTC, merged