Refactor decomposedfs to be more extensible, e.g. for the posix driver
cs3org/reva pull request #4581
Opened 2024-03-18 07:56 UTC by aduffeck

2024-04-22 12:55 UTC, butonic commented
I see where you are deleting the metadata lock ... is that conflicting with the old xattr backend? I fear that would delete the actual metadata file. 🤔 👀

2024-04-22 13:20 UTC, butonic requested changes
when deleting my storage users I don't seem to be able to get a personal space:
```
ERR failed to list storage spaces error="error reading user index: stat /home/jfd/.ocis/storage/users/indexes/by-user-id/534bb038-6f9d-4093-946f-133be61fa4e7.mpk: no such file or directory" filters=[{"Term":{"SpaceType":"project"},"type":4},{"Term":{"User":{"idp":"https://cloud.ocis.test","opaque_id":"534bb038-6f9d-4093-946f-133be61fa4e7"}},"type":6}] line=/home/jfd/Repositories/reva/internal/grpc/services/storageprovider/storageprovider.go:575 pkg=rgrpc service=storage-users status={"code":15,"message":"error listing spaces","trace":"b32ff7051e1b71f97dd10c798b02d094"} traceid=b32ff7051e1b71f97dd10c798b02d094
```

2024-04-23 06:39 UTC, aduffeck commented
@butonic Ah, ocis is still configuring the `UserLayout` variable for decomposedfs based fses, so reusing that variable for the posixfs use case was a bad idea.
I now introduced `PersonalSpacePathTemplate` and `GeneralSpacePathTemplate` instead, the ocis part (which isn't required for now since for ocis/s3ng it just default to `""` as required anyway)) is part of https://github.com/owncloud/ocis/pull/8598

2024-04-23 11:01 UTC, butonic commented
ok, this works for me as well. But lets make sure the ocis CI does not choke: https://github.com/owncloud/ocis/pull/8935

2024-04-23 13:58 UTC, butonic commented
I hope [this](https://drone.owncloud.com/owncloud/ocis/34077/32/5) is just flaky, rerunning ci

2024-05-02 08:01 UTC, aduffeck commented
@butonic the merge is green at https://github.com/owncloud/ocis/pull/9038 now. Good to go?

2024-05-02 11:31 UTC, butonic approved these changes

2024-05-02 11:31 UTC, merged

2024-05-02 11:32 UTC, butonic commented
@aduffeck do you bump reva in ocis?

2024-05-02 14:54 UTC, aduffeck commented
Sure thing: https://github.com/owncloud/ocis/pull/9050