gateway(sharing-ng): Check for remaing space manager before removing grant
cs3org/reva pull request #4585
Opened 2024-03-18 16:37 UTC by rhafer

This check is already done by the ocs sharing implementaion, but for the move to the graph API base sharing implementation we'd want to have it in a more central place.

2024-03-20 16:10 UTC, kobergj requested changes
The code looks fine, but are we really sure we want to do this? This is moving business logic to the gateway service. Previously that was a no-go as gateway should be dumb. Did this change?

cc @butonic

2024-03-20 16:20 UTC, rhafer commented
> The code looks fine, but are we really sure we want to do this? This is moving business logic to the gateway service. Previously that was a no-go as gateway should be dumb. Did this change?

I kind of discussed this already with @butonic . It's not optimal but it is for sure better than the checks duplicated at the higher levels (i.e. ocs and graph). Any idea what would be a better place for those checks. The usersharepovider in the gateway is already full of business logic because it needs to deal with the differences between space permissions and "real" shares. This change falls into the same category.

2024-03-20 18:26 UTC, butonic commented
Services infront of CS3 should just be protocol adapters. The business logic should be behind the CS3 gateway facade. It can be in the gateway or in a driver. From the outside that should be irrelevant.

If we actually split the CS3 API into two parts:
1. an actively managed space registry and
2. a storage provider
the gateway would be deployed twice. Actually, it might become obsolete and the functionality could move to middle wares and interceptors. 🤔 At least conceptually that should be the architecture. A real deployment would share the gateway and deploy it together with the space registry and storage provider.

Note that the CS3 API just defines Interfaces it does not say every API should be deployed in a dedicated service. It is meant to swap out implementations of clearly defined APIs.

2024-03-21 08:16 UTC, kobergj approved these changes

2024-03-22 09:37 UTC, merged