disallow reserved names
cs3org/reva pull request #4740
Opened 2024-06-25 09:11 UTC by butonic

We now disallow the reserved `..` and `.` filenames. They are only allowed as destinations of move or copy operations.

supersedes https://github.com/cs3org/reva/pull/4721

2024-06-25 09:23 UTC, kobergj requested changes

2024-06-25 09:23 UTC, kobergj commented on internal/http/services/owncloud/ocdav/validation.go
> +	if err := notReserved()(name); err != nil {
This is mostly the same code as in `ValidateDestination`. Why not just
```golang
return ValidateDestination(name, append(validators, notReserved())
```

2024-06-25 11:19 UTC, saw-jan commented
```feature
      | dav-path-version | file-name | http-status-code |
      | old              | /.        | 500              |
        Failed step: Then the HTTP status code should be "500"
        HTTP status code 400 is not the expected value 500
        Failed asserting that 400 matches expected '500'.
```
need test adjustment in ocis. and for that we need this to be merged first and then reva bump in ocis

2024-07-02 15:15 UTC, kobergj approved these changes

2024-07-03 05:59 UTC, merged