Refactoring of /home
cs3org/reva pull request #4940
Opened 2024-11-15 12:26 UTC by glpatcern

This is work in progress to restore #4911 in full.

- [ ] Check why the eos storage provider returns 404 on PROPFIND
- [ ] Remove eoshomewrapper and consolidate to a single eos storage provider

2024-12-03 10:07 UTC, jessegeens commented on internal/grpc/services/storageprovider/storageprovider.go
> -	if err != nil {
Why is the error handling gone here? `unwrap` can still return an error right?

2025-02-05 13:10 UTC, jouvin commented
Fixes https://github.com/cs3org/reva/issues/5069

2025-03-25 12:44 UTC, glpatcern commented
Fixes #601

2025-05-06 12:21 UTC, jessegeens requested changes

2025-05-06 12:21 UTC, jessegeens commented on internal/grpc/services/gateway/storageprovider.go
>  		return &gateway.InitiateFileDownloadResponse{
Let's maybe also log this?

2025-05-06 12:21 UTC, jessegeens commented on internal/grpc/services/gateway/storageprovider.go
> +	return s.delete(ctx, req)
Can we not directly embed this in here?

2025-05-06 12:21 UTC, jessegeens commented on internal/grpc/services/gateway/storageprovider.go
>  	if utils.IsRelativeReference(req.Ref) {
why the check if you do the same thing in both cases?

2025-05-06 12:21 UTC, jessegeens commented on internal/grpc/services/gateway/storageprovider.go
> +	return s.initiateFileUpload(ctx, req)
Can we not directly embed this?

2025-05-06 12:21 UTC, jessegeens commented on internal/grpc/services/gateway/storageprovider.go
> +	return s.move(ctx, req)
Can we not directly embed this in here?

2025-05-06 12:21 UTC, jessegeens commented on internal/grpc/services/gateway/storageprovider.go
> +	return s.stat(ctx, req)
Same comment here:
a) Why the check for relative reference if we don't use it?
b) it's just a call to `stat`, so why even split into `Stat` and `stat`?

2025-05-06 12:21 UTC, jessegeens commented on internal/grpc/services/gateway/storageprovider.go
> +	return s.listContainer(ctx, req)
No need to embed

2025-05-06 12:21 UTC, jessegeens commented on internal/grpc/services/storageprovider/storageprovider.go
> +	if fs == nil {
Should `getFS` not return an error if `fs` is `nil`?

2025-05-06 12:21 UTC, jessegeens commented on internal/http/services/owncloud/ocs/handlers/cloud/capabilities/uploads.go
> +	/*
Do we need to keep the comment?

2025-05-07 10:13 UTC, glpatcern commented on internal/grpc/services/gateway/storageprovider.go
>  		return &gateway.InitiateFileDownloadResponse{
Actually this Stat is redundant, because in `initiateFileDownload` we already call `s.find()`!

2025-05-07 10:23 UTC, glpatcern commented on internal/grpc/services/storageprovider/storageprovider.go
> +	if fs == nil {
`getFS` returns `f(ctx, c.Drivers[c.Driver])`, which itself may return `nil`

2025-05-07 10:51 UTC, glpatcern commented on internal/http/services/owncloud/ocs/handlers/cloud/capabilities/uploads.go
> +	/*
Good question, I'd say yes for now if we have to resurrect support for TUS.

2025-05-07 10:52 UTC, glpatcern commented
@rawe0 if you commit your fix it would be great, and then @jessegeens please have a look again - there was indeed quite more stuff to consolidate/drop!

2025-05-21 13:39 UTC, jessegeens approved these changes

2025-05-21 13:39 UTC, merged